apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    type: web
spec:
  template:
    metadata:
      name: pod1
      labels:
        type: web
    spec:
      containers:
       - name: c1
         image: shreya123manna/hello-world-nginx
         ports:
           - containerPort: 80
      imagePullSecrets:
       - name: my-dockerhub-secret
  replicas: 2
  selector:
    matchLabels:
      type: web
